config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("logout", views.log_out, name="logout"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
]

templates/partials/nav.html
    {% load static %}
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src={% static "assets/img/navbar-logo.svg" %} alt="" /></a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu<i class="fas fa-bars ml-1"></i></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#">Profile</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#">Upload</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url "users:logout" %}">Log out</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url "users:login" %}">Log in</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

templates/partials/social_login.html
{% load static %}
<div>
    <a href="{% url 'users:github-login' %}">
        <img class="mt-10" src="{% static 'assets/img/github_login.png' %}"></img>
    </a>
</div>