config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("logout", views.log_out, name="logout"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.shortcuts import reverse
from django.template.loader import render_to_string

# Create your models here.


class User(AbstractUser):
    
    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
    )
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

'''
    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify ajungbooks Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return
'''

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "Email", "class": "form-control"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        )
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                print("wrong")
                self.add_error("email", forms.ValidationError("잘못된 이메일 또는 비밀번호!입니다."))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("잘못된 이메일! 또는 비밀번호입니다."))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("email",)

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "email", "class": "form-control"})
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호", "class": "form-control"}
        )
    )
    password1 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 확인", "class": "form-control"}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("비밀번호가 다릅니다.")
        else:
            if password_validation.validate_password(password, password1) is not None:
                raise forms.ValidationError("invalid password")
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.views.generic import FormView, DetailView, UpdateView, View
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse, render
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms, models, mixins

# Create your views here.


class LoginView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def log_out(request):
    messages.info(request, "로그아웃 되었습니다.")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")
    initial = {"first_name": "", "last_name": "", "email": ""}

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        # user.verify_email()
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do add succes message
    except models.User.DoesNotExist:
        # to do add error message
        pass
    return redirect(reverse("core:home"))


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "avatar",
        # "oasis",
        # "student_number",
    )
    success_message = "프로필이 수정되었습니다."

    def get_object(self, queryset=None):
        return self.request.user

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["first_name"].widget.attrs = {"placeholder": "Nickname"}
        return form


class UpdatePasswordView(
    mixins.EmailLoginOnlyView,
    mixins.LoggedInOnlyView,
    SuccessMessageMixin,
    PasswordChangeView,
):

    template_name = "users/update-password.html"
    success_message = "비밀번호가 변경되었습니다."

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"placeholder": "현재 비밀번호"}
        form.fields["new_password1"].widget.attrs = {"placeholder": "새 비밀번호"}
        form.fields["new_password2"].widget.attrs = {"placeholder": "비밀번호 확인"}
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()


def github_login(request):
    client_id = os.environ.get("GH_ID")
    print(client_id)
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException()
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    if profile_json.get("email") is None:
                        email = profile_json.get("bio")
                    else:
                        email = profile_json.get("email")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException()
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=email,
                            first_name=name,
                            email=email,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException()
        else:
            raise GithubException()
    except GithubException:
        return redirect(reverse("users:login"))

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>COFENDER | Log In </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href={% static 'login/images/icons/favicon.ico' %} />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/animate/animate.css' %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/animsition/css/animsition.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/select2/select2.min.css' %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/daterangepicker/daterangepicker.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/css/util.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'login/css/main.css' %}>
<!--========================================MADE BY Colorlib========================================-->
</head>
<body>
		<div class="limiter form-group">
			<div class="container-login100">
				<div class="wrap-login100 p-t-50 p-b-90">
					<form class="login100-form validate-form flex-sb flex-w" method="POST" action="{% url "users:login" %}">
						{% csrf_token %}
						<span class="login100-form-title p-b-51">
							Login
						</span>

						
						<div class="wrap-input100 validate-input m-b-16" data-validate = "Username is required">
							<input class="form-control input100" type="email" name="email" placeholder="Email"/>
							<span class="focus-input100"></span>
						</div>
						
						
						<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
							<input class="form-control input100" type="password" name="password" placeholder="Password"/>
							<span class="focus-input100"></span>
						</div>
						
						<div class="flex-sb-m w-full p-t-3 p-b-24">
							<div class="contact100-form-checkbox">
								<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
								<label class="label-checkbox100" for="ckb1">
									<a href="https://www.youtube.com/watch?v=ph-w3BAUQhA">remember me</a>
								</label>
							</div>

							<div>
								<a href={% url "users:signup"%} class="txt1">
									sign up
								</a>
							</div>
						</div>

						<div class="container-login100-form-btn m-t-17">
							<button class="login100-form-btn" type="submit">
								Login
							</button>
							{% include "partials/social_login.html" %}
						</div>
				</div>
			</div>
		</div>
	</form>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src={% static "login/vendor/jquery/jquery-3.2.1.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/animsition/js/animsition.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "login/vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/select2/select2.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/daterangepicker/moment.min.js" %}></script>
	<script src={% static "login/vendor/daterangepicker/daterangepicker.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/countdowntime/countdowntime.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/js/main.js" %}></script>

</body>
</html>

templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>COFENDER | Sign Up </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href={% static 'login/images/icons/favicon.ico' %} />
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/animate/animate.css' %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/animsition/css/animsition.min.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/select2/select2.min.css' %}>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href={% static 'login/vendor/daterangepicker/daterangepicker.css' %}>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'login/css/util.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'login/css/main.css' %}>
<!--========================================MADE BY Colorlib========================================-->
</head>
<body>
	<form method="POST" action="{% url "users:signup" %}">
		{% csrf_token %}
		<div class="limiter">
			<div class="container-login100">
				<div class="wrap-login100 p-t-50 p-b-90">
					<form class="login100-form validate-form flex-sb flex-w">
						<span class="login100-form-title p-b-51">
							Sign Up
						</span>

						
						<div class="wrap-input100 validate-input m-b-16" data-validate = "Username is required">
							<input class="form-control input100" type="email" name="email" placeholder="Email">
							<span class="focus-input100"></span>
						</div>
						
						
						<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
							<input class="form-control input100" type="password" name="password" placeholder="Password">
							<span class="focus-input100"></span>
						</div>
						
                        <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
							<input class="form-control input100" type="password" name="password1" placeholder="Confirm Password">
							<span class="focus-input100"></span>
						</div>

						<div class="flex-sb-m w-full p-t-3 p-b-24">
							<div class="contact100-form-checkbox">
								<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
								<label class="label-checkbox100" for="ckb1">
									Remember me
								</label>
							</div>

							<div>
								<a href={% url "users:login"%} class="txt1">
									Log in
								</a>
							</div>
						</div>

						<div class="container-login100-form-btn m-t-17">
							<button class="login100-form-btn">
								Login
							</button>
							{% include "partials/social_login.html" %}
						</div>

					</form>
				</div>
			</div>
		</div>
	</form>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src={% static "login/vendor/jquery/jquery-3.2.1.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/animsition/js/animsition.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "login/vendor/bootstrap/js/bootstrap.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/select2/select2.min.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/daterangepicker/moment.min.js" %}></script>
	<script src={% static "login/vendor/daterangepicker/daterangepicker.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/vendor/countdowntime/countdowntime.js" %}></script>
<!--===============================================================================================-->
	<script src={% static "login/js/main.js" %}></script>

</body>
</html>

templates/users/update-password.html
<h1>update password</h1>

templates/users/update-profile.html
<h1>update-profile</h1>